### ISSUE TITLE
 Failed to read the 'responseText' property from 'XMLHttpRequest': The value is only accessible if the object's 'responseType' is '' or 'text' (was 'json').

### ISSUE THREAD

**Issue by yl1988** [YGYOOO/ajax-interceptor#79]
在 mac chrome 浏览器启用时报错：
main.js:67 Uncaught DOMException: Failed to read the 'responseText' property from 'XMLHttpRequest': The value is only accessible if the object's 'responseType' is '' or 'text' (was 'json').
    at myXHR.get [as responseText] (chrome-extension://nhpjggchkhnlbgdfcbgpdpkifemomkpg/pageScripts/main.js:67:59)
    at eval (webpack-internal:///./node_modules/@babel/runtime/helpers/objectSpread2.js:34:41)
    at Array.forEach (<anonymous>)
    at _objectSpread2 (webpack-internal:///./node_modules/@babel/runtime/helpers/objectSpread2.js:33:41)
    at f.onreadystatechange (webpack-internal:///./node_modules/lc-ui-web-base/lib/lc-ui-web-base.umd.min.js:155:674387)
    at xhr.onreadystatechange (chrome-extension://nhpjggchkhnlbgdfcbgpdpkifemomkpg/pageScripts/main.js:46:62)

电脑配置：m1芯片，内核arm

chrome 版本：版本 104.0.5112.101（正式版本） （arm64）
<img width="840" alt="企业微信截图_775c7457-d307-425a-bbf0-4a6028018962" src="https://user-images.githubusercontent.com/31236125/186089013-4572b7b2-def3-4770-a92e-3222118b313e.png">

项目node版本：v14.20.0
项目Vue版本：2.6.14

**Comment by YGYOOO** [comment]
你的ajax请求是不是设置了responseType = 'json'，然后又取了responseText的值（这时只能取），这个是本身写法有问题，你试下把chrome插件关掉是不是也同样报错。类似下面这样的代码本身就是不对的：
var xhr = new XMLHttpRequest();
xhr.responseType = "json";

xhr.open("get", "//api.bilibili.com/studio/growup/web/version/check?csrf=f4c0ca7cc3e00b48a619410f1243de77&s_locale=zh_CN");
xhr.send()
xhr.onload = function() {
    console.log(xhr.response);
    console.log(xhr.responseText); // responseType是json时不能取responseText，除非去掉上面的responseType设置（默认是text）
}
